import './globals.css';

import { Suspense } from 'react';

import { Inter } from 'next/font/google';

import Loading from './loading';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Clika-charts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading/>}>{children}</Suspense>
        </body>
    </html>
  )
}
